### ISSUE TITLE
a problem with downloading  openAD

### ISSUE THREAD

**Issue by BartlomiejBekier** [DLR-SL/CPACS-IFARX#18]
Hi all,
I am a new member of this project (as employee of Institute of aviation).  I tried to download the Aircraft Design software - openAD   from this link https://dlrmax.dlr.de/get/27cd3d1b-5df7-5002-b98d-9af701d152dc/  but the download file is no longer available there. Can you send me a new link? Thank you in advance for your help.
Best wishes,
Bartłomiej Bekier

**Comment by MarAlder** [comment]
https://dlrmax.dlr.de/get/5aad006a-edf0-5c2a-9c30-4207020324a7/

**Comment by MarAlder** [comment]
Hi Bartłomiej,

can you send me an message with your eMail address? Then I can send you the link.

**Comment by BartlomiejBekier** [comment]
Thank you, but I have this link already :)
